parameters:
    ez_core_extra.themes.list: []
    ez_core_extra.themes.design_list: []
    ez_core_extra.themes.path_map: {}
    ez_core_extra.themes.override_paths: []

    ez_core_extra.default.design: ~
