parameters:

services:
    ez_core_extra.view_template_listener:
        class: Lolautruche\EzCoreExtraBundle\EventListener\ViewTemplateListener
        arguments: ["@ezpublish.config.resolver", "@ezpublish.config.dynamic_setting.parser"]
        tags:
            - { name: kernel.event_subscriber }

    ez_core_extra.twig_engine:
        class: Lolautruche\EzCoreExtraBundle\Templating\ThemeAwareTwigEngine
        public: false
        decorates: templating.engine.twig
        arguments: ["@ez_core_extra.twig_engine.inner"]
        calls:
            - [setCurrentDesign, ["$design;ez_core_extra$"]]
