parameters:

services:
    ez_core_extra.view_template_listener:
        class: Lolautruche\EzCoreExtraBundle\EventListener\ViewTemplateListener
        arguments: ["@ezpublish.config.resolver", "@ezpublish.config.dynamic_setting.parser"]
        tags:
            - { name: kernel.event_subscriber }

    ez_core_extra.template_name_resolver:
        class: Lolautruche\EzCoreExtraBundle\Templating\ThemeTemplateNameResolver
        arguments: ["$design;ez_core_extra$"]
        lazy: true

    ez_core_extra.twig_theme_loader:
        class: Lolautruche\EzCoreExtraBundle\Templating\TwigThemeLoader
        public: false
        decorates: twig.loader.filesystem
        arguments: ["@ez_core_extra.template_name_resolver", "@ez_core_extra.twig_theme_loader.inner"]
