language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
    - 5.6
    - 7.0

branches:
    only:
        - master
        - /^\d+\.\d+$/

before_script:
    - phpenv config-rm xdebug.ini
    - composer install 

script:
    - phpunit
